language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
os:
  - linux
  - osx
env:
  - TOX_ENV=lint
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=docs

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  email:
    - rahul.rrixe@gmail.com